using BracketCityPuzzle

puzzle = Puzzle("2025-11-02",
                raw"""Charles [[[to  continued...]aver's [un[rich baby's [what [Scouts with a [[something a director yells]ter that is a common metaphor for mass-produced unoriginality] empire]s Just Want To Have]d 💰]worthy artist]struction project]me, Gogh, or Halen vehicle?] Doren [word after [a bad one may be [not right] in your mouth] or before [top without s[🗽 [de force or de [Nice place] 🚴‍♀️]ist ➡️  ⬅️ door 🕳️]s] 🧪]ifies before Congress""")

show_puzzle(preduce(puzzle))

set_answer(puzzle, 12, "left")
set_answer(puzzle, 11, "taste")
set_answer(puzzle, 3, "be")
set_answer(puzzle, 9, "cut")
set_answer(puzzle, 16, "france")
set_answer(puzzle, 15, "tour")
set_answer(puzzle, 14, "trap")
set_answer(puzzle, 13, "tube")
set_answer(puzzle, 10, "test")
set_answer(puzzle, 8, "cookie")
set_answer(puzzle, 7, "girl")
set_answer(puzzle, 6, "fun")
set_answer(puzzle, 5, "trust")
set_answer(puzzle, 4, "con")
set_answer(puzzle, 2, "dam")
set_answer(puzzle, 1, "van")

show_puzzle(preduce(puzzle))

